#!/usr/bin/env bash
set -euo pipefail

# Register the rod motor by the serial number exposed by its own USB adapter.
# The operator must insert only the rod motor while this script is waiting.

RULE_FILE='/etc/udev/rules.d/99-rodmotor.rules'
WAIT_SECONDS=90

die() {
  echo "错误：$*" >&2
  exit 1
}

list_tty_devices() {
  find /dev -maxdepth 1 -type c \( -name 'ttyUSB*' -o -name 'ttyACM*' \) -printf '%f\n' | sort
}

[[ "$(id -u)" -eq 0 ]] || die '请使用 sudo 执行。'

baseline="$(mktemp)"
trap 'rm -f "$baseline"' EXIT
list_tty_devices >"$baseline"

echo '请确认：此刻仅推书杆 USB 设备处于断开状态。'
read -r -p '按 Enter 后插入推书杆 USB 设备，脚本将等待 90 秒：'

device=''
for _ in $(seq 1 "$WAIT_SECONDS"); do
  while IFS= read -r name; do
    if ! grep -Fxq "$name" "$baseline"; then
      device="/dev/$name"
      break 2
    fi
  done < <(list_tty_devices)
  sleep 1
done

[[ -n "$device" ]] || die '未检测到新串口。请确认只插入了推书杆，然后重新执行。'

properties="$(udevadm info --query=property --name="$device")"
vendor="$(awk -F= '$1 == "ID_VENDOR_ID" { print $2 }' <<<"$properties")"
product="$(awk -F= '$1 == "ID_MODEL_ID" { print $2 }' <<<"$properties")"
serial="$(awk -F= '$1 == "ID_SERIAL_SHORT" { print $2 }' <<<"$properties")"
path="$(awk -F= '$1 == "ID_PATH" { print $2 }' <<<"$properties")"

[[ "$vendor" =~ ^[0-9A-Fa-f]{4}$ ]] || die "无法读取 $device 的 USB 厂商 ID。"
[[ "$product" =~ ^[0-9A-Fa-f]{4}$ ]] || die "无法读取 $device 的 USB 产品 ID。"

if [[ -n "$serial" ]]; then
  match="ATTRS{serial}==\"$serial\""
  identity="序列号 $serial"
elif [[ -n "$path" ]]; then
  match="ENV{ID_PATH}==\"$path\""
  identity="USB 物理路径 $path"
else
  die "无法读取 $device 的唯一序列号或 USB 路径，拒绝写入不安全的通用规则。"
fi

temp_rule="$(mktemp)"
trap 'rm -f "$baseline" "$temp_rule"' EXIT
cat >"$temp_rule" <<EOF
# Generated by register-rodmotor-device.sh for $device ($identity).
SUBSYSTEM=="tty", ATTRS{idVendor}=="$vendor", ATTRS{idProduct}=="$product", $match, SYMLINK+="rodmotor", MODE="0660", GROUP="dialout"
EOF

if [[ -e "$RULE_FILE" ]]; then
  backup="$RULE_FILE.$(date -u +%Y%m%dT%H%M%SZ).bak"
  cp -p "$RULE_FILE" "$backup"
  echo "已备份旧规则：$backup"
fi

install -o root -g root -m 0644 "$temp_rule" "$RULE_FILE"
udevadm control --reload-rules
udevadm trigger --subsystem-match=tty --action=add
sleep 1

[[ -L /dev/rodmotor ]] || die "规则已写入，但 /dev/rodmotor 未出现；请重新插入推书杆后执行 ls -l /dev/rodmotor。"
resolved="$(readlink -f /dev/rodmotor)"
[[ "$resolved" == "$device" ]] || die "/dev/rodmotor 指向 $resolved，不是刚识别的 $device；请检查其他 udev 规则。"

echo "推书杆已注册：/dev/rodmotor -> $device"
echo "规则：$RULE_FILE"
